title: Crypto Bangle Litepaper
description: "Revolutionizing the Future of Digital Transactions: A Comprehensive Guide to the Crypto Bangel Whitepaper"
author:
  name: "GPTus"
baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"
